# Generated by Django 6.0.4 on 2026-05-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="หัวข้อ")),
            ],
            options={
                "verbose_name": "หมวดหมู่",
                "verbose_name_plural": "หมวดหมู่",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="ลำดับข้อ")),
                ("body", models.TextField(verbose_name="โจทย์")),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=10, verbose_name="เฉลย"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="questions.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อสอบ",
                "verbose_name_plural": "ข้อสอบ",
                "ordering": ["number"],
            },
        ),
    ]
