# Generated by Django 6.0.5 on 2026-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.FloatField(blank=True, null=True, verbose_name="ความยาก (b)"),
        ),
        migrations.AddField(
            model_name="question",
            name="param_a",
            field=models.FloatField(blank=True, null=True, verbose_name="Parameter a"),
        ),
        migrations.AddField(
            model_name="question",
            name="param_c",
            field=models.FloatField(blank=True, null=True, verbose_name="Parameter c"),
        ),
    ]
