# Generated by Django 6.0.5 on 2026-05-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_difficulty_question_param_a_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        default="ระบบสอบออนไลน์", max_length=200, verbose_name="ชื่อรายวิชา"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        default="2569", max_length=10, verbose_name="ปีการศึกษา"
                    ),
                ),
                (
                    "num_choices",
                    models.IntegerField(
                        default=5, verbose_name="จำนวนตัวเลือก (4 หรือ 5)"
                    ),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่าการสอบ",
                "verbose_name_plural": "ตั้งค่าการสอบ",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="stem",
            field=models.TextField(blank=True, verbose_name="คำถาม (ไม่มีตัวเลือก)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="body",
            field=models.TextField(verbose_name="โจทย์ (ต้นฉบับ)"),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="ตัวเลือกที่")),
                ("body", models.TextField(blank=True, verbose_name="ข้อความตัวเลือก")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตัวเลือก",
                "verbose_name_plural": "ตัวเลือก",
                "ordering": ["number"],
                "unique_together": {("question", "number")},
            },
        ),
    ]
