# Generated by Django 6.0.5 on 2026-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_examconfig_question_stem_alter_question_body_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="examconfig",
            name="exam_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background หน้าข้อสอบ (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="home_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background หน้า Home (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="student_login_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background นักเรียน Login (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="student_register_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background นักเรียน Register (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="teacher_login_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background ครู Login (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="teacher_register_bg",
            field=models.URLField(
                blank=True, default="", verbose_name="Background ครู Register (URL)"
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="time_limit",
            field=models.IntegerField(
                default=0, verbose_name="เวลาสอบต่อข้อ (วินาที, 0=ไม่จำกัด)"
            ),
        ),
    ]
