# Generated by Django 6.0.5 on 2026-05-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_examconfig_is_results_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="เฉลย"
                    ),
                ),
                (
                    "difficulty",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ความยาก (b)"
                    ),
                ),
                (
                    "param_a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Parameter a"
                    ),
                ),
                (
                    "param_c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Parameter c"
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="questions.question",
                        verbose_name="ข้อสอบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "พารามิเตอร์ข้อสอบ",
                "verbose_name_plural": "พารามิเตอร์ข้อสอบ",
            },
        ),
    ]
