# Generated by Django 6.0.5 on 2026-05-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_questionparameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="question",
            name="param_a",
        ),
        migrations.RemoveField(
            model_name="question",
            name="param_c",
        ),
    ]
