# Generated by Django 6.0.5 on 2026-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_remove_question_correct_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="questions/",
                verbose_name="รูปภาพประกอบ",
            ),
        ),
    ]
