# Generated by Django 6.0.5 on 2026-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="examconfig",
            name="allow_retake",
            field=models.BooleanField(default=False, verbose_name="อนุญาตให้ทำข้อสอบซ้ำ"),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="question_order",
            field=models.CharField(
                choices=[
                    ("difficulty", "ง่าย → ยาก (ตาม b-parameter)"),
                    ("random", "สุ่ม"),
                    ("sequential", "ตามลำดับข้อ"),
                ],
                default="difficulty",
                max_length=20,
                verbose_name="ลำดับข้อสอบ",
            ),
        ),
        migrations.AddField(
            model_name="examconfig",
            name="questions_per_session",
            field=models.IntegerField(
                default=0, verbose_name="จำนวนข้อต่อครั้ง (0 = ทั้งหมด)"
            ),
        ),
    ]
