# Generated by Django 6.0.4 on 2026-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขประจำตัวนักเรียน"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="ชื่อ")),
                ("last_name", models.CharField(max_length=100, verbose_name="นามสกุล")),
                ("phone", models.CharField(max_length=15, verbose_name="เบอร์โทรศัพท์")),
                ("grade", models.CharField(max_length=20, verbose_name="ชั้นปี")),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "นักเรียน",
                "verbose_name_plural": "นักเรียน",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="ชื่อ")),
                ("last_name", models.CharField(max_length=100, verbose_name="นามสกุล")),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="วิชาที่สอน")),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ครู",
                "verbose_name_plural": "ครู",
            },
        ),
    ]
