# Generated by Django 6.0.5 on 2026-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="avatar",
            field=models.URLField(
                blank=True, default="", verbose_name="รูปโปรไฟล์ (URL)"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="อีเมล"
            ),
        ),
    ]
