# Generated by Django 6.0.5 on 2026-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teacher_avatar_teacher_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="รูปโปรไฟล์"
            ),
        ),
    ]
