# Generated by Django 6.0.5 on 2026-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="time_limit_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
