# Generated by Django 6.0.5 on 2026-05-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_examsession_time_limit_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="abandoned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
